# Generated by Django 5.2.5 on 2025-09-13 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('relationship_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='library',
            old_name='book',
            new_name='books',
        ),
    ]
